% Function: setup_Vars
%  
% Description: 
%   Instantiates all necessary variables for BaselineFitting, Hindcasting, 
%   and Interventions. This is the file which is edited by
%   the user for the location's data. This file will be ran which simply
%   instantiates the variables and saves them to a .mat file to be loaded.
% 
% Inputs:
%   None: Data is entered within this file.
%
% Outputs:
%   Variables are saved to files for: Baseline_IN.mat, Inter_IN.mat
% _____________________________________________________________________________

%{
 * BaselineFitting Variables
%}

% Site details: Relevant endemic regions, Country (pertains only Sub-Saharan Africa cases), Village

% country names should follow format of CountryDemogParams.csv
Countries = {'Nigeria';'Nigeria';'Nigeria';'Nigeria';'Nigeria';'Tanzania';'Egypt';'PNG'}; 
Sites = {'DokanTofa';'Piapung';'Seri';'Gbuwhen';'Maiganga';'Kirare';'Giza';'UsinoBundi'};

% Site data: Mf prevalence, blood sample volume, ABR, vector genera
% arranged in region-specific .m data files created by the user
[ DokanTofaMf,PiapungMf,SeriMf,GbuwhenMf,MaigangaMf,KirareMf,PenengMf,GizaMf,UsinoBundiMf,...
    DokanTofaCfa,PiapungCfa,SeriCfa,GbuwhenCfa,MaigangaCfa,KirareCfa,PenengCfa,GizaCfa,UsinoBundiCfa,...
    DokanTofaVol,PiapungVol,SeriVol,GbuwhenVol,MaigangaVol,KirareVol,PenengVol,GizaVol,UsinoBundiVol,...
    DokanTofaABR,PiapungABR,SeriABR,GbuwhenABR,MaigangaABR,KirareABR,PenengABR,GizaABR,UsinoBundiABR,...
    DokanTofabCulex,PiapungbCulex,SeribCulex,GbuwhenbCulex,MaigangabCulex,KirarebCulex,PenengbCulex,GizabCulex,UsinoBundibCulex]...
    = baseline_data;

% ABR range for use in each site without baseline ABR data
ABRmin = [500,500,500,500,500,500,500,500]; % Use default value, won't increase computaiton intensitivity
ABRmax = [15000,15000,15000,15000,15000,15000,15000,15000]; 

% Mf range for use in each site without baseline Mf data
minPrev = [0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02];
maxPrev = [0.50,0.50,0.50,0.50,0.50,0.50,0.50,0.50]; 

save('IN/Baseline_IN.mat', 'Countries', 'Sites',...
     'DokanTofaMf','GbuwhenMf','MaigangaMf','PiapungMf','SeriMf','KirareMf','PenengMf','GizaMf','UsinoBundiMf',...
     'DokanTofaCfa','GbuwhenCfa','MaigangaCfa','PiapungCfa','SeriCfa','KirareCfa','PenengCfa','GizaCfa','UsinoBundiCfa',...
     'DokanTofaVol','GbuwhenVol','MaigangaVol','PiapungVol','SeriVol','KirareVol','PenengVol','GizaVol','UsinoBundiVol',...
     'DokanTofaABR','GbuwhenABR','MaigangaABR','PiapungABR','SeriABR','KirareABR','PenengABR','GizaABR','UsinoBundiABR',...
     'DokanTofabCulex','GbuwhenbCulex','MaigangabCulex','KirarebCulex','PenengbCulex','GizabCulex','UsinoBundibCulex',...
     'PiapungbCulex','SeribCulex','ABRmin','ABRmax','minPrev','maxPrev');

%{
 * Interventions Variables
%}

% Uses Regions, Countries, and sites from above

% Site data: Mf prevalence, blood sample volume, MDA regimen, MDA frequency,...
% MDA coverage, number of years of treatment, vector control, switch year
% arranged in region-specific .m data files created by the user
[ DokanTofaMf,PiapungMf,SeriMf,GbuwhenMf,MaigangaMf,KirareMf,GizaMf,UsinoBundiMf,...
    DokanTofaCfa,PiapungCfa,SeriCfa,GbuwhenCfa,MaigangaCfa,KirareCfa,GizaCfa,UsinoBundiCfa,...
    DokanTofaL3,PiapungL3,SeriL3,GbuwhenL3,MaigangaL3,KirareL3,GizaL3,UsinoBundiL3,...
    DokanTofaMfAge,PiapungMfAge,SeriMfAge,GbuwhenMfAge,MaigangaMfAge,KirareMfAge,GizaMfAge,UsinoBundiMfAge,...
    DokanTofaCfaAge,PiapungCfaAge,SeriCfaAge,GbuwhenCfaAge,MaigangaCfaAge,KirareCfaAge,GizaCfaAge,UsinoBundiCfaAge,...
    DokanTofaYear,PiapungYear,SeriYear,GbuwhenYear,MaigangaYear,KirareYear,GizaYear,UsinoBundiYear,...
    DokanTofaReg,PiapungReg,SeriReg,GbuwhenReg,MaigangaReg,KirareReg,GizaReg,UsinoBundiReg,...
    DokanTofaFreq,PiapungFreq,SeriFreq,GbuwhenFreq,MaigangaFreq,KirareFreq,GizaFreq,UsinoBundiFreq,...
    DokanTofaMDACov,PiapungMDACov,SeriMDACov,GbuwhenMDACov,MaigangaMDACov,KirareMDACov,GizaMDACov,UsinoBundiMDACov,...
    DokanTofaNumYears,PiapungNumYears,SeriNumYears,GbuwhenNumYears,MaigangaNumYears,KirareNumYears,GizaNumYears,UsinoBundiNumYears,...
    DokanTofaVC,PiapungVC,SeriVC,GbuwhenVC,MaigangaVC,KirareVC,GizaVC,UsinoBundiVC,...
    DokanTofaSwitchYear,PiapungSwitchYear,SeriSwitchYear,GbuwhenSwitchYear,MaigangaSwitchYear,KirareSwitchYear,GizaSwitchYear,UsinoBundiSwitchYear,...
    DokanTofaITNCov,PiapungITNCov,SeriITNCov,GbuwhenITNCov,MaigangaITNCov,KirareITNCov,GizaITNCov,UsinoBundiITNCov,...
    DokanTofaITNYear,PiapungITNYear,SeriITNYear,GbuwhenITNYear,MaigangaITNYear,KirareITNYear,GizaITNYear,UsinoBundiITNYear,...
    DokanTofaIRSCov,PiapungIRSCov,SeriIRSCov,GbuwhenIRSCov,MaigangaIRSCov,KirareIRSCov,GizaIRSCov,UsinoBundiIRSCov]...
    = PostIntv_data_SSA;

save IN/Inter_IN.mat Countries Sites ...
    DokanTofaMf PiapungMf SeriMf GbuwhenMf MaigangaMf KirareMf GizaMf UsinoBundiMf...
    DokanTofaCfa PiapungCfa SeriCfa GbuwhenCfa MaigangaCfa KirareCfa GizaCfa UsinoBundiCfa ...
    DokanTofaL3 PiapungL3 SeriL3 GbuwhenL3 MaigangaL3 KirareL3 GizaL3 UsinoBundiL3 ...
    DokanTofaMfAge PiapungMfAge SeriMfAge GbuwhenMfAge MaigangaMfAge KirareMfAge GizaMfAge UsinoBundiMfAge...
    DokanTofaCfaAge PiapungCfaAge SeriCfaAge GbuwhenCfaAge MaigangaCfaAge KirareCfaAge GizaCfaAge UsinoBundiCfaAge...
    DokanTofaYear PiapungYear SeriYear GbuwhenYear MaigangaYear KirareYear GizaYear UsinoBundiYear...
    DokanTofaReg PiapungReg SeriReg GbuwhenReg MaigangaReg KirareReg GizaReg UsinoBundiReg...
    DokanTofaFreq PiapungFreq SeriFreq GbuwhenFreq MaigangaFreq KirareFreq GizaFreq UsinoBundiFreq...
    DokanTofaMDACov PiapungMDACov SeriMDACov GbuwhenMDACov MaigangaMDACov KirareMDACov GizaMDACov UsinoBundiMDACov ...
    DokanTofaNumYears PiapungNumYears SeriNumYears GbuwhenNumYears MaigangaNumYears KirareNumYears GizaNumYears UsinoBundiNumYears ...
    DokanTofaVC PiapungVC SeriVC GbuwhenVC MaigangaVC KirareVC GizaVC UsinoBundiVC...
    DokanTofaSwitchYear PiapungSwitchYear SeriSwitchYear GbuwhenSwitchYear MaigangaSwitchYear KirareSwitchYear GizaSwitchYear UsinoBundiSwitchYear...
    DokanTofaITNCov PiapungITNCov SeriITNCov GbuwhenITNCov MaigangaITNCov KirareITNCov GizaITNCov UsinoBundiITNCov...
    DokanTofaITNYear PiapungITNYear SeriITNYear GbuwhenITNYear MaigangaITNYear KirareITNYear GizaITNYear UsinoBundiITNYear ...    
    DokanTofaIRSCov PiapungIRSCov SeriIRSCov GbuwhenIRSCov MaigangaIRSCov KirareIRSCov GizaIRSCov UsinoBundiIRSCov ...
    DokanTofaVol GbuwhenVol MaigangaVol PiapungVol SeriVol KirareVol GizaVol UsinoBundiVol
